<<<<<<< HEAD
# Generated by Django 5.2.7 on 2025-10-23 03:41
=======
# Generated by Django 5.2.7 on 2025-10-21 17:38
>>>>>>> 172d2643f3f0ed09ed85e79112b0bfcfc497ae0d

import core.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deliverable_type', models.CharField(choices=[('report', 'PDF Report'), ('notebook', 'Reproducible Notebook'), ('code', 'Code Bundle'), ('data_log', 'Data Processing Log'), ('sow', 'Statement of Work'), ('qa_report', 'QA Report')], max_length=50)),
                ('file', models.FileField(upload_to='deliverables/%Y/%m/%d/')),
                ('filename', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_id', models.CharField(default=core.models.generate_project_id, max_length=20, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('stage', models.CharField(choices=[('proposal', 'Proposal'), ('data_analysis', 'Data Analysis'), ('literature_review', 'Literature Review'), ('methodology', 'Methodology'), ('full_project', 'Full Project')], max_length=20)),
                ('support_type', models.CharField(choices=[('sample_size', 'Sample Size Calculation'), ('analysis_plan', 'Analysis Plan'), ('statistical_analysis', 'Statistical Analysis'), ('data_cleaning', 'Data Cleaning'), ('methodology_review', 'Methodology Review'), ('report_writing', 'Report Writing'), ('reproducible_notebook', 'Reproducible Notebook'), ('other', 'Other')], max_length=50)),
                ('research_area', models.CharField(max_length=255)),
                ('sample_size', models.IntegerField(blank=True, null=True)),
                ('preferred_methods', models.TextField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('budget_range', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('qa', 'QA Review'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('disputed', 'Disputed')], default='submitted', max_length=20)),
                ('confirms_lawful_use', models.BooleanField(default=False)),
                ('confirms_data_rights', models.BooleanField(default=False)),
                ('irb_approval_provided', models.BooleanField(default=False)),
                ('agreed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PseudonymousUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alias', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('magic_token', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('magic_token_expires', models.DateTimeField(blank=True, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_analyst', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DownloadToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('is_one_time', models.BooleanField(default=True)),
                ('deliverable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_tokens', to='core.deliverable')),
            ],
        ),
        migrations.AddField(
            model_name='deliverable',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='core.project'),
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='project_files/%Y/%m/%d/')),
                ('filename', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField()),
                ('file_type', models.CharField(max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.project')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pseudonymoususer')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='assigned_analyst',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_projects', to='core.pseudonymoususer'),
        ),
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='core.pseudonymoususer'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.project')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pseudonymoususer')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='deliverable',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pseudonymoususer'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('project_submitted', 'Project Submitted'), ('project_accepted', 'Project Accepted'), ('status_changed', 'Status Changed'), ('file_uploaded', 'File Uploaded'), ('file_downloaded', 'File Downloaded'), ('deliverable_uploaded', 'Deliverable Uploaded'), ('payment_processed', 'Payment Processed'), ('message_sent', 'Message Sent'), ('project_rejected', 'Project Rejected'), ('dispute_filed', 'Dispute Filed')], max_length=50)),
                ('details', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='core.project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pseudonymoususer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['project_id'], name='core_projec_project_96ab66_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['client', 'status'], name='core_projec_client__f4eed2_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='core_projec_status_2020cc_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['project', 'action'], name='core_auditl_project_64007d_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'action'], name='core_auditl_user_id_4f5b78_idx'),
        ),
    ]
