# Generated by Django 5.2.7 on 2025-10-23 09:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_authtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='pseudonymoususer',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
